### PR TITLE
micro-reddit 

### PR DESCRIPTION
**Pull request by SajjadAhmad14**
- This project is built on the basis of Reddit functionality
- User can have many Posts
- User can Comment on many Posts
- User can add posts and comment on any post using rails console
- User, Post, and Comment have associations among them.

### CODE REVIEW

**Review by rOluochKe — CHANGES_REQUESTED** [review]
Hello @SajjadAhmad14 and @MkrtichSargsyan 
### You have done well so far :clap: However, you have a few issues to fix:-
- [ ] Install all the required dependencies, add github actions and configure. [Follow this guide](https://github.com/microverseinc/linters-config/tree/master/ror)
- [ ] Add rails db:create as part of the installation process in the readme file
### Make the change and submit for another code review. Good luck.
- Happy coding!

**Comment by SajjadAhmad14** [comment]
> Hello @SajjadAhmad14 and @MkrtichSargsyan
> 
> ### You have done well so far  However, you have a few issues to fix:-
> * [ ]  Install all the required dependencies, add github actions and configure. [Follow this guide](https://github.com/microverseinc/linters-config/tree/master/ror)
> * [ ]  Add rails db:create as part of the installation process in the readme file
> 
> ### Make the change and submit for another code review. Good luck.
> * Happy coding!

**Comment by SajjadAhmad14** [comment]
Hi! So what kind of dependencies are you asking to install?

**Review by MarioDena — APPROVED** [review]
Hello! Great work Implementing the requested chabges! 🥇 

#Project approved 🟢 

Cheers!

Code Review by Mario Enrique Delgado Naranjo

**Pull request merged**
